"""
Latency Utility Module

- Computes end-to-end latency (event time → processing time)
- Logs latency data to CSV for offline analysis
- Ensures reproducibility via persistent logging

Design Notes:
- CSV logging is used for simplicity and portability
- Each row represents a single event's latency measurement
- File flushing ensures durability (important for crash scenarios)
"""

import csv
import os


CSV_FILE = "results/latency_log.csv"


def init_csv():
    """
    Initialize CSV file for latency logging

    - Creates results directory if not exists
    - Writes header if file is new
    """
    os.makedirs("results", exist_ok=True)

    if not os.path.exists(CSV_FILE):
        with open(CSV_FILE, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["event_time", "receive_time", "latency"])


def calculate_latency(event_time, receive_time):
    """
    Compute end-to-end latency

    Args:
        event_time (float): timestamp generated by producer
        receive_time (float): timestamp at consumer

    Returns:
        float | None: latency in seconds
    """
    try:
        return float(receive_time) - float(event_time)
    except Exception as e:
        print(f"Latency calculation error: {e}")
        return None


def log_latency(event_time, receive_time, latency):
    """
    Append latency record to CSV

    Args:
        event_time (float)
        receive_time (float)
        latency (float)
    """
    try:
        if latency is None:
            return  # skip invalid data

        with open(CSV_FILE, "a", newline="") as f:
            writer = csv.writer(f)

            writer.writerow([float(event_time), float(receive_time), float(latency)])

            f.flush()

    except Exception as e:
        print(f"Failed to write CSV: {e}")
